# Generated by Django 2.1.5 on 2019-03-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('userpwd', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WechatId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puid', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('selected_friends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.SelectedFriends')),
                ('selected_groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.SelectedGroups')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='we_chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.WechatId'),
        ),
    ]
