# Generated by Django 2.1.5 on 2019-03-05 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='we_chat_id',
        ),
        migrations.AddField(
            model_name='wechatid',
            name='user_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.UserInfo'),
            preserve_default=False,
        ),
    ]
