<<<<<<< HEAD
# Generated by Django 2.1.7 on 2019-04-11 10:31
=======
# Generated by Django 2.1.7 on 2019-03-26 13:30
>>>>>>> acb8c86e5915306157008056c793ddc27ee3fd97

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=32, unique=True, verbose_name='插件名称')),
                ('pdescribe', models.TextField(verbose_name='插件描述')),
<<<<<<< HEAD
                ('plug', models.FileField(upload_to='static/upload/Plugs', verbose_name='插件文件')),
                ('msg_type', models.CharField(choices=[('Text', '文本'), ('Map', '位置'), ('Card', '名片'), ('Note', '提示'), ('Sharing', '分享'), ('Picture', '图片'), ('Recording', '语音'), ('Attachment', '文件'), ('Video', '视频'), ('Friends', '好友请求'), ('System', '系统')], default='Text', max_length=36)),
                ('wake_word', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='触发关键字')),
=======
                ('plug_path', models.FileField(upload_to='static/upload/Plugs', verbose_name='插件文件')),
                ('wake_word', models.CharField(max_length=128)),
>>>>>>> acb8c86e5915306157008056c793ddc27ee3fd97
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedFriends',
            fields=[
                ('fid', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedGroups',
            fields=[
                ('gid', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> acb8c86e5915306157008056c793ddc27ee3fd97
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('userpwd', models.CharField(max_length=32)),
                ('uemail', models.EmailField(max_length=254)),
                ('isActive', models.BooleanField(default=True)),
<<<<<<< HEAD
                ('clues', models.TextField(blank=True, max_length=550, null=True)),
                ('clues_status', models.BooleanField(default=True)),
                ('timer', models.TimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('repetition', models.CharField(blank=True, choices=[('everyday', '每天'), ('once', '单次')], max_length=32, null=True)),
                ('timer_send_isActive', models.BooleanField(blank=True, null=True)),
=======
>>>>>>> acb8c86e5915306157008056c793ddc27ee3fd97
            ],
        ),
        migrations.CreateModel(
            name='UserPlugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('isActive', models.BooleanField(default=False)),
=======
                ('isActive', models.BooleanField(default=True)),
>>>>>>> acb8c86e5915306157008056c793ddc27ee3fd97
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.Plugs')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='WechatId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puid', models.CharField(max_length=32, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('user_info', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='databases.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='selectedgroups',
            name='wechat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.WechatId'),
        ),
        migrations.AddField(
            model_name='selectedfriends',
            name='wechat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.WechatId'),
        ),
    ]
