# Generated by Django 2.1.7 on 2019-03-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('userpwd', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WechatId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puid', models.CharField(max_length=32, unique=True)),
                ('status', models.NullBooleanField(default=True)),
                ('user_info', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='databases.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='selectedgroups',
            name='wechat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.WechatId'),
        ),
        migrations.AddField(
            model_name='selectedfriends',
            name='wechat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.WechatId'),
        ),
    ]
